### ISSUE TITLE
Fix: Google icon not showing

### ISSUE THREAD

**Issue by SaiCorporation** [SaiCorporation/Google-Adv#1]
Hi guys, we have got a new issue for in the code as the line `<a href image show>Google<a>` is not showing the google ADV logo on the (enhanced) homepage. Please give me a fix. Thank you.

**Comment by SaiCorporation** [comment]
And the diff

**Comment by adventure-games** [comment]
### Here is a fix. Instructions written below.
- hit the key `.`
- get to the file you want to fix, and do `Ctrl + F`
- type in `<img class="lnXdpd" alt="Google" height="92" src="./Google_files/googlelogo_color_272x92dp.png" srcset="/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png 1x, /images/branding/googlelogo/2x/googlelogo_color_272x92dp.png 2x" width="272" data-atf="1" data-frt="0">`.
- Change `./Google_files/googlelogo_color_272x92dp.png` to the image you need.
Well, that is how I have fixed this type of issue in the past.

**Comment by SaiCorporation** [comment]
Thank you @adventure-games
